name: update1Password
on:
  #schedule:
  #  - cron: '* 0 * * 1-5'
  workflow_dispatch:
jobs:
  update1Password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Obtain user data
        env: 
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.onepassword }}
        run: op user list --account poloniex.1password.com --format=json | op user get - --format=json | jq -s -r > 1passwordUsers.json
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'         
      - name: Install google apps script
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: Obtain google credentials
        env:
          google: ${{ secrets.google }}
        run: |
          echo $google | base64 --decode > googlecreds.json 
      - name: Run python script
        run: python gsheets/1passwordUsers.py